# Generated by Django 3.1.7 on 2021-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0003_auto_20210331_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
