# Generated by Django 3.1.7 on 2021-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0005_auto_20210331_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='final_stock',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='final_stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='back_to_usine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='back_to_usine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='material_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Material defectuous'),
        ),
    ]
