# Generated by Django 3.1.7 on 2021-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0006_auto_20210331_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
