# Generated by Django 3.1.7 on 2021-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0013_auto_20210528_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='material_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Material status'),
        ),
    ]
