# Generated by Django 3.1.7 on 2021-05-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0018_auto_20210529_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(default='Internal', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
