# Generated by Django 3.1.7 on 2021-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_stock', '0019_auto_20210529_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reference',
            field=models.CharField(default=4, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='reference',
            field=models.CharField(default=5, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Niveau seuil'),
        ),
    ]
