# Generated by Django 3.1.7 on 2021-06-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20210613_1508'),
        ('internal_stock', '0022_auto_20210607_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Provider'),
            preserve_default=False,
        ),
    ]
