# Generated by Django 3.1.7 on 2021-06-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20210615_0811'),
        ('internal_stock', '0023_stock_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Provider'),
        ),
    ]
