# Generated by Django 3.1.7 on 2021-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210528_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'verbose_name_plural': 'Stock Histories'},
        ),
        migrations.AddField(
            model_name='stock',
            name='back_to_usine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='material_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Material status'),
        ),
        migrations.AddField(
            model_name='stock',
            name='observations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='back_to_usine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='material_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Material status'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='observations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
