# Generated by Django 3.1.7 on 2021-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210528_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='material_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Material Defectuous'),
        ),
    ]
