# Generated by Django 3.1.7 on 2021-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210529_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(default='Int', max_length=50),
            preserve_default=False,
        ),
    ]
