# Generated by Django 3.1.7 on 2021-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210529_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reference',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
