# Generated by Django 3.1.7 on 2021-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_stock_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='reference',
            field=models.CharField(default=3, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
