# Generated by Django 3.1.7 on 2021-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_stockhistory_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
