# Generated by Django 3.1.7 on 2021-06-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20210615_0811'),
        ('store', '0017_auto_20210607_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='providers.provider', verbose_name='Provider'),
            preserve_default=False,
        ),
    ]
