# Generated by Django 3.1.7 on 2021-05-29 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_auto_20210528_1506'),
        ('internal_stock', '0016_auto_20210528_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('society', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('6\\d{8}', 'This field is incorrect')])),
                ('fax', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('6\\d{8}', 'This field is incorrect')])),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_ht', models.CharField(blank=True, max_length=20)),
                ('total_tva', models.CharField(blank=True, max_length=20)),
                ('total_ttc', models.CharField(blank=True, max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('internal_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal_stock.stock')),
                ('yassa_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
            },
        ),
    ]
