# Generated by Django 3.1.7 on 2021-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_ht',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_ttc',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_tva',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
