# Generated by Django 3.1.7 on 2021-06-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_ht',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_ttc',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_tva',
            field=models.PositiveBigIntegerField(),
        ),
    ]
