# Generated by Django 3.1.7 on 2021-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20210607_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_ht',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_ttc',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tva',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
