# Generated by Django 3.1.7 on 2021-06-13 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20210613_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='mobile',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('6[9|7|6|5|2]\\d{7}', 'This field is incorrect')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('6[9|7|6|5|2]\\d{7}', 'This field is incorrect')]),
        ),
    ]
